#!/bin/bash
  VNAME="Enigma2 VPN Killswitch"
  VINFO="Killswitch V1.4"
    case "$1" in
    start)
    killswitch
      checkps=(pgrep tnl_ks)
                if  [ -n "$checkps" ]; then
                        pkill tnl_ks
                fi
    ;;
    stop)
    pkill killswitch
    ;;
    restart)
    $0 stop
    sleep 1
    $0 start
    ;;
    version)
    echo "$VNAME"
    ;;
    info)
    echo "$VINFO"
    ;;
    *)
      echo "usage: $0 start|stop|restart" >&2
    exit 1
   ;;
  esac
  exit 1
