#!/bin/bash -x
clear
### presets

local_dns=$(cat /etc/resolv.conf | grep nameserver | awk '/nameserver/ {print $2}' | head -n 1)
checkps=$(pgrep tnl_ks)
                if  [ -n "$checkps" ]; then
                        pkill tnl_ks
                fi

###define proto
if [ -e /etc/wireguard/*.conf ]; then
        binary="wireguard"
elif [ -e /etc/openvpn/*.conf ]; then
        binary="openvpn"
fi

### function

while true :; do
route_default=$(ip route | awk '/default/')
        if  [ -n "$route_default" ]; then
                if [[ $binary == "wireguard" ]]; then
                        ip route del default
                fi
        fi
check_vpn=$(ip -o link show | awk -F': ' '{print $2}' | grep -E  'wg|tun')
        if  [ -n "$check_vpn" ]; then
                if [[ $binary == "wireguard" ]]; then
                        ping_check=$(ping -c 2 -I $check_vpn 1.1.1.1 | grep time)
                                if  [ -z "$ping_check" ]; then
                                        _date=$(date +"%F %H:%M:%S")
                                        echo -e "$_date wg0 offline" >>  /tmp/wireguard.log
                                        /etc/init.d/$binary stop
                                        /etc/init.d/$binary start
                                fi
                elif [[ $binary == "openvpn" ]]; then
                        ping_check=$(ping -c 2 -I $check_vpn 1.1.1.1 | grep time)
                                if  [ -z "$ping_check" ]; then
                                        _date=$(date +"%F %H:%M:%S")
                                        echo -e "$_date tun0 offline" >>  /tmp/openvpn.log
                                        pkill openvpn
                                        vpn start openvpn
                                fi
        fi
 
        else
                if [[ $binary == "wireguard" ]]; then
                        _date=$(date +"%F %H:%M:%S")
                        echo -e "$_date wg0 offline" >>  /tmp/wireguard.log
                        /etc/init.d/$binary start
                elif [[ $binary == "openvpn" ]]; then
                        _date=$(date +"%F %H:%M:%S")
                        echo -e "$_date tun0 offline" >>  /tmp/openvpn.log
                        vpn start openvpn
                fi
        fi





done
