#!/bin/bash
RED='\033[0;31m'
ORANGE='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m'
#by LouMu
### Preset ###
wg_menu_check() {
menu_check_av_wg=$(opkg list wireguard-tools | grep wireguard-tools)
        if  [ -n "$menu_check_av_wg" ]
                then
                        echo -e "${GREEN}1) WireGuard install${NC}"
                        echo -e "${GREEN}2) WireGuard Killswitch${NC}"
                else
                        echo -e "${RED}1) WireGuard install (not possible)${NC}"
                        echo -e "${RED}2) WireGuard Killswitch (not possible)${NC}"
        fi
}
ovpn_menu_check() {
menu_check_av_ovpn=$(opkg list openvpn | grep openvpn)
        if  [ -n "$menu_check_av_ovpn" ]
                then
                        echo -e "${GREEN}4) OpenVPN install (coming soon)${NC}"
                        echo -e "${GREEN}5) OpenVPN Killswitch (coming soon)${NC}"
                else
                        echo -e "${RED}4) OpenVPN install (not possible)${NC}"
                        echo -e "${RED}5) OpenVPN Killswitch (not possible)${NC}"
        fi
}


wg_av() {
check_install_wg=$(opkg list-installed wireguard-tools | grep wireguard-tools)
        if  [ -n "$check_install_wg" ]
                then
                        echo -e "${ORANGE}WireGuard installation already found!${NC}"
                else
                        check_wg_av=$(opkg list wireguard-tools | grep wireguard-tools)
                                if  [ -n "$check_wg_av" ]
                                        then
                                                echo -e "${GREEN}WireGuard installation possible!${NC}"
                                        else
                                                echo -e "${RED}Sorry! WireGuard installation impossible!${NC}"
                                fi
        fi
}
ovpn_av() {
check_install_ovpn=$(opkg list-installed openvpn | grep openvpn)
        if  [ -n "$check_install_ovpn" ]
                then
                        echo -e "${ORANGE}OpenVPN installation already found!${NC}"
                else
                        check_ovpn_av=$(opkg list openvpn | grep openvpn)
                                if  [ -n "$check_ovpn_av" ]
                                        then
                                                echo -e "${GREEN}OpenVPN installation possible!${NC}"
                                        else
                                                echo -e "${RED}Sorry! OpenVPN installation impossible!${NC}"
                                fi
        fi
}
my_header() {
        clear
	echo "+-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+"
	echo "|E|n|i|g|m|a|2| |N|e|t|w|o|r|k| |T|o|o|l|b|o|x|"
	echo "+-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+"
}
wrong_opt() {
        echo "Wrong option!"
        sleep 2
        clear
}
sys_update() {
        opkg update > /dev/null 2>&1
}

### WireGuard ###
wg_proof_inst() {
        echo -e "${ORANGE}checking system compatibility...${NC}"
proof_wg_inst=$(opkg list wireguard-tools | grep wireguard-tools)
        if  [ -n "$proof_wg_inst" ]
                then
                        echo -e "${GREEN}...install WireGuard${NC}"
                        opkg install wireguard-tools
                else
                        echo -e "${RED}Sorry! WireGuard installation impossible!${NC}"
                        exit 0
        fi
}
wg_read_conf() {
echo "Pipe in wireguard config, or paste and it ctrl-d when done"
wgconf=$(cat)

cat <<EOF > /etc/wireguard/wg0.conf
${wgconf}
EOF
chmod 644 /etc/wireguard/wg0.conf
}
wg_trim_conf() {
sed -i '/DNS/d' /etc/wireguard/wg0.conf
sed -i 's/,.*//' /etc/wireguard/wg0.conf
sed -i 's/\/0/\/1/g' /etc/wireguard/wg0.conf
}
wg_start() {
        echo -e "${GREEN}...install update-rc.d${NC}"
        opkg install update-rc.d > /dev/null 2>&1
        echo -e "${GREEN}...create startscript${NC}"
        wget -O /etc/init.d/wireguard https://raw.githubusercontent.com/muplagama/enigma2-vpn-toolbox/main/rc/wireguard > /dev/null 2>&1
        echo -e "${GREEN}...enable startscript${NC}"
	chmod +x /etc/init.d/wireguard
        update-rc.d wireguard defaults
	sleep 1
        /etc/init.d/wireguard start
}
wg_check_connect() {
ping_check=$(ping -c 2 -I wg0 "1.1.1.1" | grep time)
        if  [ -n "$ping_check" ]
                then
                        echo -e "${GREEN}WireGuard is up${NC}"
			sleep 10
                else
                        echo -e "${RED}Error! WireGuard is down${NC}"
			sleep 10
        fi
}

### WireGuard Killswitch ###
wg_ks_download() {
check_wg_ks=$(opkg list-installed wireguard-tools | grep wireguard)
	if [ -n "$check_wg_ks" ]
		then
	        echo -e "${GREEN}...download files${NC}"
		sleep 1
		wget -O /etc/wireguard/killswitch.sh https://raw.githubusercontent.com/muplagama/enigma2-wireguard-killswitch/main/killswitch.sh  > /dev/null 2>&1
		chmod +x /etc/wireguard/killswitch.sh
		wget -O /etc/init.d/killswitch https://raw.githubusercontent.com/muplagama/enigma2-wireguard-killswitch/main/killswitch > /dev/null 2>&1
		chmod +x /etc/init.d/killswitch
		else
		echo -e "${RED}Error! No WireGuard installation found.. please install before!${NC}"
		sleep 5
		exit 0
	fi
}
enable_wg_ks() {
	echo -e "${GREEN}...enable autostart${NC}"
	sleep 2
	/etc/init.d/killswitch enable  > /dev/null 2>&1
}
check_wg_ks() {
	check_wg_ks_ps=$(pgrep killswitch.sh)
	if  [ -n  "$check_wg_ks_ps" ]
	then
        	echo -e "${GREEN}Success: Killswitch is running.${NC}"
        	sleep 5
	else
		echo -e "${RED}Error! Killswitch not running.${NC}"
		sleep 5
	fi
}


uninstall_wg_ks() {
        echo -e "${GREEN}...uninstall WireGuard killswitch${NC}"
        sleep 2
        /etc/init.d/killswitch uninstall  > /dev/null 2>&1
}



mainmenu() {
my_header
wg_av
ovpn_av
echo -e ""
echo -e "##### Menu #####"
echo -e ""
wg_menu_check
echo -e "3) uninstall WireGuard Killswitch"
echo -e ""
ovpn_menu_check
echo -e ""
echo -e "0) Exit"
echo -e ""
read -p "choose an Option: " main </dev/tty

case $main in
1)
        sys_update
        wg_proof_inst
        wg_read_conf
        wg_trim_conf
        wg_start
        wg_check_connect
        mainmenu
        ;;
2)
	wg_ks_download
	enable_wg_ks
	check_wg_ks
        mainmenu
        ;;
3)
	uninstall_wg_ks
	mainmenu
	;;
4)
        mainmenu
        ;;
5)
        mainmenu
        ;;
0)
        echo "bye bye"
        exit 0
        ;;
*)
        wrong_opt
        mainmenu
        ;;

esac
}
mainmenu
