#!/bin/bash -x
VNAME="Enigma2 OpenVPN"
  VINFO="Enigma2 OpenVPN v1"
  BINARY=/usr/sbin/openvpn
  CONFIG=/etc/openvpn/openvpn.conf
  case "$1" in
    start)
    if  [ -f "$CONFIG" ]
    then
     echo "starting OpenVPN"
     $BINARY --daemon  --config $CONFIG
     else
     echo "openvpn.conf not found"
    fi
   ;;
    stop)
        echo "stopping OpenVPN"
        openvpn_pid=$(pgrep openvpn)
        kill $openvpn_pid
           ;;
    restart)
    $0 stop
    sleep 1
    $0 start
   ;;
    version)
    echo "$VNAME"
   ;;
    info)
    echo "$VINFO"
   ;;
    *)
    echo "usage: $0 start|stop|restart|version|info" >&2
    exit 1
   ;;
  esac
  exit 0
