#!/bin/bash
RED='\033[0;31m'
ORANGE='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m'
#by tnl.ninja
### Preset ###
wg_menu_check() {
menu_check_av_wg=$(opkg list wireguard-tools | grep wireguard-tools)
        if  [ -n "$menu_check_av_wg" ]
                then
                        echo -e "${GREEN}1) WireGuard install                     // opkg based systems ${NC}"
                       
                else
                        echo -e "${RED}1) WireGuard install (not possible)    // opkg based systems${NC}"
                        
        fi
}
ovpn_menu_check() {
menu_check_av_ovpn=$(opkg list openvpn | grep openvpn)
        if  [ -n "$menu_check_av_ovpn" ]
                then
                        echo -e "${GREEN}2) OpenVPN install		       // opkg based systems${NC}"
                        
                else
                        echo -e "${RED}2) OpenVPN install (not possible)                     // opkg based systems${NC}"
                        
        fi
}


wg_av() {
check_install_wg=$(opkg list-installed wireguard-tools | grep wireguard-tools)
        if  [ -n "$check_install_wg" ]
                then
                        echo -e "${ORANGE}WireGuard installation already found!${NC}"
                else
                        check_wg_av=$(opkg list wireguard-tools | grep wireguard-tools)
                                if  [ -n "$check_wg_av" ]
                                        then
                                                echo -e "${GREEN}WireGuard installation possible!${NC}"
                                        else
                                                echo -e "${RED}Sorry! WireGuard installation impossible!${NC}"
                                fi
        fi
}
ovpn_av() {
check_install_ovpn=$(opkg list-installed openvpn | grep openvpn)
        if  [ -n "$check_install_ovpn" ]
                then
                        echo -e "${ORANGE}OpenVPN installation already found!${NC}"
                else
                        check_ovpn_av=$(opkg list openvpn | grep openvpn)
                                if  [ -n "$check_ovpn_av" ]
                                        then
                                                echo -e "${GREEN}OpenVPN installation possible!${NC}"
                                        else
                                                echo -e "${RED}Sorry! OpenVPN installation impossible!${NC}"
                                fi
        fi
}
my_header() {
        clear
	echo "+-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+"
	echo "|E|n|i|g|m|a|2| |N|e|t|w|o|r|k| |T|o|o|l|b|o|x|"
	echo "+-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+"
	echo "                                   by tnl.ninja"
        echo "                                               "
}
wrong_opt() {
        echo "Wrong option!"
        sleep 2
        clear
}
sys_update() {
        opkg update > /dev/null 2>&1
	wait $!
}
ks_download() {
	        echo -e "${GREEN}...download files${NC}"
		wget -O /bin/killswitch https://raw.githubusercontent.com/muplagama/enigma2-vpn-toolbox/main/killswitch/killswitch_v2  > /dev/null 2>&1
	wait $!
		chmod +x /bin/killswitch
		wget -O /etc/init.d/tnl_ks https://raw.githubusercontent.com/muplagama/enigma2-vpn-toolbox/main/killswitch/killswitch_start > /dev/null 2>&1
	wait $!
		chmod +x /etc/init.d/tnl_ks
		}

vpnstatus(){
		wget -O /bin/vpn https://raw.githubusercontent.com/muplagama/enigma2-vpn-toolbox/main/status/vpn_dev
	
#		wget -O /bin/vpn https://raw.githubusercontent.com/muplagama/enigma2-vpn-toolbox/main/status/vpn > /dev/null 2>&1
		chmod +x /bin/vpn
}

### WireGuard ###
wg_proof_inst() {
        echo -e "${ORANGE}checking system compatibility...${NC}"
proof_wg_inst=$(opkg list wireguard-tools | grep wireguard-tools)
        if  [ -n "$proof_wg_inst" ]
                then
                        echo -e "${GREEN}...install WireGuard${NC}"
                        opkg install wireguard-tools
                else
                        echo -e "${RED}Sorry! WireGuard installation impossible!${NC}"
                        exit 0
        fi
}


##### OpenVPN
ovpn_proof_inst() {
        echo -e "${ORANGE}checking system compatibility...${NC}"
proof_ovpn_inst=$(opkg list openvpn | grep openvpn)
        if  [ -n "$proof_ovpn_inst" ]
                then
                        echo -e "${GREEN}...install Openvpn${NC}"
                        opkg install openvpn
			opkg -f openvpn remove > /dev/null 2>&1
                else
                        echo -e "${RED}Sorry! Openvpn installation impossible!${NC}"
                        exit 0
        fi
}


##### Dreambox VPN Manager
dreambox_install() {
dm_grep=$(cat /etc/hostname)
if [ $dm_grep = dreambox ]
        then
        echo "Installing Dreambox One Version"
	cd /tmp
	curl -o /tmp/enigma2-plugin-extensions-vpnmanager_1.2.0.deb -JLO https://github.com/muplagama/enigma2-vpn-toolbox/blob/main/deb/enigma2-plugin-extensions-vpnmanager_1.2.0.deb?raw=true
	apt-get update && dpkg -i /tmp/*.deb && apt-get -f install
	curl -o /tmp/WireGuardONE.zip -JLO https://github.com/muplagama/enigma2-vpn-toolbox/blob/main/deb/WireGuardONE.zip?raw=true
	unzip WireGuardONE.zip
	python /tmp/WireGuard/WireGuard.py
elif [ $dm_grep = DMTwo ]
        then
        echo "Installing Dreambox Two Version"
	cd /tmp
	curl -o /tmp/enigma2-plugin-extensions-vpnmanager_1.2.0.deb -JLO https://github.com/muplagama/enigma2-vpn-toolbox/blob/main/deb/enigma2-plugin-extensions-vpnmanager_1.2.0.deb?raw=true
	apt-get update && dpkg -i /tmp/*.deb && apt-get -f install
	curl -o /tmp/WireGuardTWO.zip -JLO https://github.com/muplagama/enigma2-vpn-toolbox/blob/main/deb/WireGuardTWO.zip?raw=true
	unzip WireGuardTWO.zip
	python /tmp/WireGuard/WireGuard.py
else
        echo "not installable on this system"
        exit 0
fi
}

mainmenu() {
my_header
wg_av
ovpn_av
echo -e ""
echo -e "##### Menu #####"
echo -e ""
wg_menu_check
ovpn_menu_check
echo -e ""
#echo -e "6) VPN Manager + Wireguard - DM One/Two // TESTING"
echo -e "0) Exit"
echo -e ""
echo -e "Info: killswitch disabled by default, can be enabled in post installation"
echo -e ""
read -p "choose an Option: " main </dev/tty

case $main in
1)
sys_update
vpnstatus
wg_proof_inst
vpn newconf wireguard
vpn setdns
mainmenu
;;
2)
sys_update
vpnstatus
vpn newconf openvpn
vpn setdns
mainmenu
;;
3)
mainmenu
;;
4)	
dreambox_install
mainmenu
;;
0)
echo "bye bye"
rm /tmp/enigma-vpn-installer
exit 0
;;
*)
wrong_opt
mainmenu
;;

esac
}
mainmenu
