#!/bin/bash
RED='\033[0;31m'
ORANGE='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m'

### binary select ###
if   [[ $2 == "wireguard" ]]; then
        binary="wireguard"
elif [[ $2 == "openvpn" ]]; then
        binary="openvpn"
elif [[ $2 == "killswitch" ]]; then
        binary="tnl_ks"
fi
### DNS SETTINGS 
select_dns1() {
clear
echo -e "${ORANGE}PRIMARY DNS${NC}"
echo "1) cloudflare     1.1.1.1"
echo "2) quad9          9.9.9.9"
echo "3) google         8.8.8.8"
echo "4) adguard        176.103.130.130"
read  -p "select primary dns: " bqdl </dev/tty
case $bqdl in
[1]*)
dns1=1.1.1.1
;;
[2]*)
dns1=9.9.9.9
;;
[3]*)
dns1=8.8.8.8
;;
[4]*)
dns1=176.103.130.130
;;
*)
echo "none selected"
exit 0
;;
esac
}
select_dns2() {
echo ""
echo -e "${ORANGE}Secondary DNS${NC}"
echo "1) cloudflare     1.0.0.1"
echo "2) quad9          149.112.112.112"
echo "3) google         8.8.4.4"
echo "4) adguard        176.103.130.131"
read  -p "select secondary dns: " bqdl </dev/tty
case $bqdl in
[1]*)
dns2=1.0.0.1
;;
[2]*)
dns2=149.112.112.112
;;
[3]*)
dns2=8.8.4.4
;;
[4]*)
dns2=176.103.130.131
;;
*)
echo "none selected"
exit 0
;;
esac
}

push_dns() {
chattr -i /etc/resolv.conf
rm /etc/resolv.conf
cat <<EOF > /etc/resolv.conf
nameserver $dns1
nameserver $dns2
EOF

chattr +i /etc/resolv.conf

echo -e "${ORANGE}dns set: nameserver $dns1 nameserve $dns2${NC}"
}

case "$1" in
        start)
        vpn_start
        ;;
        silent)
        start_silent
        ;;
        stop)
        vpn_stop
        ;;
        enable)
        vpn_enable
        ;;
        disable)
        vpn_disable
        ;;
        remove)
        vpn_remove
        ;;
        newconf)
        new_conf
        ;;
        setdns)
        select_dns1
        select_dns2
        push_dns
        ;;
        status)
        interface_check
        link_check
        location_check
        ks_check
        ;;
    *)
    echo "usage:"
    echo "vpn start wireguard|openvpn|killswitch">&2
    echo "vpn stop wireguard|openvpn|killswitch">&2
    echo "vpn enable wireguard|openvpn|killswitch">&2
    echo "vpn disable wireguard|openvpn|killswitch">&2
    echo "vpn remove wireguard|openvpn|killswitch">&2
    echo "vpn newconf wireguard|openvpn">&2
    echo "vpn status" >&2
    exit 1
   ;;
  esac
  exit 0
