#!/bin/bash
RED='\033[0;31m'
ORANGE='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m'

clear
     	echo ""
        echo -e "${ORANGE}VPN status check${NC}"
        echo""
interface_check() {
        echo -e "${ORANGE}Interface status check${NC}"

        iface=$(ip -o link show | awk -F': ' '{print $2}' | grep wg; ip -o link show | awk -F': ' '{print $2}' | grep tun)
        if  [ -n "$iface" ]; then
                echo -e "${GREEN} $iface VPN Interface is up${NC}"
        else
            	echo -e "${RED} $iface VPN Interface is down${NC}"
        exit 0
	fi
}
link_check(){
	echo -e "${ORANGE}$iface link check${NC}"
        link=$( ping -c 3 -I $iface 1.0.0.1 | grep time | grep ttl | wc -l )
        if [ $link -eq 0 ]; then
                echo -e "${RED} $iface VPN link check failed${NC}"
                exit 0
        else
            	echo -e "${GREEN} $iface VPN link check success${NC}"
        fi
}

location_check(){
        echo -e "${ORANGE}$iface VPN location check${NC}"
        vpn_ip=$(curl -s ipinfo.io/ip)
        echo -e "${GREEN} VPN IP:	 "$vpn_ip"${NC}"
        vpn_country=$(curl -s ipinfo.io/country)
        echo -e "${GREEN} VPN Country:  "$vpn_country"${NC}"
        vpn_city=$(curl -s ipinfo.io/city)
        echo -e "${GREEN} VPN City:     "$vpn_city"${NC}"
}



interface_check
link_check
location_check
